#!/usr/bin/env python3
"""Generate the public skills catalog for the VS Code Skills Store.

All public skills are loaded from this repository's skills/ folder so the
GitHub Pages site is self-contained.

Only skills that have been reviewed as public-safe should be listed in CATALOG.
"""
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
LOCAL_SKILLS = REPO_ROOT / 'skills'
OUT = REPO_ROOT / 'skills-data.js'

CATALOG = [
    dict(id='pandas-data-analysis', name='Pandas Data Analysis', icon='📊', category='Data Science', tags=['pandas','python','dataframe','csv','analysis','matplotlib'], version='1.0.0'),
    dict(id='fastapi-development', name='FastAPI Development', icon='⚡', category='Backend', tags=['fastapi','python','rest','api','pydantic','jwt'], version='1.0.0'),
    dict(id='github-actions-ci', name='GitHub Actions CI/CD', icon='🔄', category='DevOps', tags=['github','ci-cd','actions','yaml','automation','testing'], version='1.0.0'),
    dict(id='cad-solidworks-automation', name='CAD SolidWorks Automation', icon='🧰', category='CAD / Mechanical', tags=['solidworks','cad','mechanical','vba','automation','drawings','assemblies'], version='1.0.0'),
    dict(id='robotics-ros2', name='Robotics with ROS 2', icon='🤖', category='Robotics', tags=['ros2','robotics','python','simulation','sensors','control','rviz','gazebo'], version='1.0.0'),
    dict(id='stock-market-analysis', name='Stock Market Analysis with Python', icon='📈', category='Finance / Data', tags=['stocks','yfinance','pandas','finance','backtesting','portfolio','risk'], version='1.0.0'),
    dict(id='open-meteo-weather-api', name='Open-Meteo Weather API', icon='🌦️', category='Free API', tags=['api','weather','open-meteo','json','python','javascript','teaching'], version='1.0.0'),
    dict(id='israel-home-front-alerts-api', name='Israel Home Front Alerts Data', icon='🚨', category='Free API', tags=['api','israel','emergency','alerts','json','teaching','safety'], version='1.0.0'),
    dict(id='israel-transport-gtfs-api', name='Israel Public Transport GTFS API', icon='🚆', category='Free API', tags=['api','israel','transport','gtfs','trains','buses','realtime','data'], version='1.0.0'),
    dict(id='nasa-open-apis', name='NASA Open APIs', icon='🛰️', category='Free API', tags=['api','nasa','space','apod','json','python','teaching'], version='1.0.0'),
    dict(id='wikipedia-api-lesson', name='Wikipedia API', icon='📚', category='Free API', tags=['api','wikipedia','wikimedia','mediawiki','search','json','teaching'], version='1.0.0'),
    dict(id='openstreetmap-nominatim-api', name='OpenStreetMap Nominatim API', icon='🗺️', category='Free API', tags=['api','maps','openstreetmap','geocoding','location','json','teaching'], version='1.0.0'),
    dict(id='rest-countries-api', name='REST Countries API', icon='🌍', category='Free API', tags=['api','countries','geography','json','flags','teaching'], version='1.0.0'),
    dict(id='openai-api-setup', name='OpenAI API Setup and Cost Tracking', icon='🔑', category='API', tags=['api','openai','ai','dotenv','python','cost','tokens','security'], version='1.0.0'),
]


def get_description(content: str) -> str:
    """Extract description from YAML frontmatter."""
    # Try multiline description: > style
    m = re.search(r'(?s)description:\s*>\s*\n(.*?)(?:\n\w|\n---)', content)
    if m:
        lines = [l.strip() for l in m.group(1).splitlines() if l.strip()]
        return ' '.join(lines)
    # Try inline description: "value"
    m = re.search(r'description:\s*["\']?(.+)', content)
    if m:
        return m.group(1).strip().strip('"\'')
    return ''

def build_js():
    parts = []
    parts.append(
        '/* =============================================================================\n'
        '   VS Code Skills Store — Skill Catalog\n'
        '   Auto-generated by generate-skills-data.py\n'
        '   Add new skills here. Each entry is displayed as a card in the store.\n'
        '============================================================================= */\n'
        '\n'
        'window.SKILLS_DATA = [\n'
    )

    entries = []
    for meta in CATALOG:
        skill_path = LOCAL_SKILLS / meta['id'] / 'SKILL.md'
        if not skill_path.exists():
            print(f'  SKIPPING (not found): {meta["id"]}')
            continue

        raw = skill_path.read_text(encoding='utf-8', errors='replace')
        desc = get_description(raw)

        # Escape content for JS template literal: escape backticks and ${
        content_escaped = raw.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')

        tags_js = ', '.join(f"'{t}'" for t in meta['tags'])
        name_esc = meta['name'].replace("'", "\\'")
        desc_esc = desc.replace("'", "\\'").replace('\n', ' ')

        entry = (
            f"\n  // ── {meta['name']} ──\n"
            f"  {{\n"
            f"    id:          '{meta['id']}',\n"
            f"    name:        '{name_esc}',\n"
            f"    description: '{desc_esc}',\n"
            f"    category:    '{meta['category']}',\n"
            f"    tags:        [{tags_js}],\n"
            f"    icon:        '{meta['icon']}',\n"
            f"    author:      'Skills Store',\n"
            f"    version:     '{meta['version']}',\n"
            f"    content: `{content_escaped}`\n"
            f"  }}"
        )
        entries.append(entry)
        print(f'  OK: {meta["id"]} ({len(raw.splitlines())} lines)')

    parts.append(',\n'.join(entries))
    parts.append('\n\n];\n')
    return ''.join(parts)

if __name__ == '__main__':
    print('Generating skills-data.js ...')
    js = build_js()
    OUT.write_text(js, encoding='utf-8')
    size_kb = OUT.stat().st_size // 1024
    print(f'\nGenerated: {OUT}')
    print(f'Size: {size_kb} KB')
    print(f'Skills: {len(CATALOG)} entries')
